apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: k8s
  namespace: prometheus-test
spec:
  replicas: 2
  serviceAccountName: prometheus
  securityContext: {}
  serviceMonitorNamespaceSelector:
    matchNames:
      - prometheus-test
      - dev-test
  serviceMonitorSelector:
    matchExpressions:
      - key: k8s-app
        operator: Exists
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  alerting:
    alertmanagers:
      - namespace: prometheus-test
        name: alertmanager-main
        port: web
